#!/usr/bin/env python3
"""
Generates one amazon.aws.aws_ec2 dynamic-inventory file per
(account, region) pair from accounts.yml, so scaling to a new account
or region is a data change in accounts.yml, not a playbook or
inventory change.
"""
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ACCOUNTS_FILE = os.path.join(HERE, "..", "accounts.yml")
OUT_DIR = os.path.join(HERE, "generated")

TEMPLATE = """\
# AUTO-GENERATED by inventory/generate_inventory.py -- do not hand-edit.
plugin: amazon.aws.aws_ec2
aws_profile: {alias}
regions:
  - {region}
filters:
  tag:Monitoring: enabled
  instance-state-name: running
keyed_groups:
  - key: tags.Environment | default('untagged')
    prefix: env
  - key: tags.BusinessUnit | default('untagged')
    prefix: bu
compose:
  ansible_aws_ssm_profile: "'{alias}'"
  account_alias: "'{alias}'"
  account_id: "'{account_id}'"
hostnames:
  - tag:Name
  - instance-id
"""


def main() -> None:
    with open(ACCOUNTS_FILE) as f:
        data = yaml.safe_load(f)

    os.makedirs(OUT_DIR, exist_ok=True)
    # Clear stale files so a removed account/region drops out cleanly.
    for f in os.listdir(OUT_DIR):
        if f.endswith(".aws_ec2.yml"):
            os.remove(os.path.join(OUT_DIR, f))

    count = 0
    for acct in data["accounts"]:
        for region in acct["regions"]:
            filename = f"{acct['alias']}_{region}.aws_ec2.yml"
            path = os.path.join(OUT_DIR, filename)
            with open(path, "w") as out:
                out.write(TEMPLATE.format(
                    alias=acct["alias"],
                    region=region,
                    account_id=acct["account_id"],
                ))
            count += 1

    print(f"Generated {count} inventory file(s) in {OUT_DIR}")


if __name__ == "__main__":
    main()
